namespace Bld.LibcameraNet.Interop;

public enum PropertyId
{
    LOCATION = 1,
    ROTATION = 2,
    MODEL = 3,
    UNIT_CELL_SIZE = 4,
    PIXEL_ARRAY_SIZE = 5,
    PIXEL_ARRAY_OPTICAL_BLACK_RECTANGLES = 6,
    PIXEL_ARRAY_ACTIVE_AREAS = 7,
    SCALER_CROP_MAXIMUM = 8,
    SENSOR_SENSITIVITY = 9,
    SYSTEM_DEVICES = 10,

    COLOR_FILTER_ARRANGEMENT = 10001,
}